# 1장 파이썬 머신러닝 이해  



[머신러닝 완벽 가이드] 책을 기반으로 제가 정리하고 요약한 내용입니다.  
1장은 머신러닝의 기초인 넘파이와 판다스에 대한 개념입니다.

## 넘파이
넘파이는 배열 기반의 연산은 물론이고 다양한 데이터 핸들링 기능을 제공합니다.

In [1]:
import numpy as np # 넘파이 모듈 임포트

### ndarray 데이터 타입

In [2]:
array1 = np.array([1,2,3]) 
# 넘파이의 array()함수는 파이썬의 리스트와 같은 인자를 ndarray로 변환하는 기능 수행
print('array1 type:',type(array1))
print('array1 type 형태:',array1.shape)

array2 = np.array([[1,2,3],
                   [4,5,6]])
print('array2 type:',type(array2))
print('array2 type 형태:',array2.shape)

array1 type: <class 'numpy.ndarray'>
array1 type 형태: (3,)
array2 type: <class 'numpy.ndarray'>
array2 type 형태: (2, 3)


In [3]:
list1 = [1,2,3]
print(type(list1))
array1 = np.array(list1)
print(type(array1))
print(array1.dtype) #ndarray내의 데이터타입은 .dtype 으로 확인 가능

<class 'list'>
<class 'numpy.ndarray'>
int32


In [4]:
list2 = [1,2,'test']
array2 = np.array(list2)
print(array2.dtype)

list3 = [1,2,3.1]
array3 = np.array(list3)
print(array3.dtype) 

<U11
float64


다른 데이터 유형이 ndarray로 변경되면 데이터 크기가 더 큰 데이터 타입으로 형 변환이 적용됩니다.

In [5]:
list3 = [1, 2, 3]
array4 =np.array(list3)
print(array4.dtype)
array4 =array4.astype(float)
print(array4.dtype)

int32
float64


ndarray 내 데이터값의 타입 변경은 astype()을 이용해 가능합니다.

### ndarray 생성

In [6]:
arange = np.arange(10)
print(arange)
print(arange.dtype)
print(arange.shape)

[0 1 2 3 4 5 6 7 8 9]
int32
(10,)


arange()는 0부터 함수 인자 값 -1까지의 값을 순차적으로 ndarray의 데이터값으로 변환해줍니다.  
start, stop을 지정해서 원하는 값부터 시작한 연속 값을 부여할 수 있습니다.

In [7]:
zeros = np.zeros((3,2))
print(zeros)
print(zeros.dtype)
print(zeros.shape)

[[0. 0.]
 [0. 0.]
 [0. 0.]]
float64
(3, 2)


zeros()는 함수 인자로 튜플 형태의 shape값을 입력하면 모든 값을 0으로 채운 해당 shape를 가진 ndarray를 반환합니다. 이와 유사하게 ones()는 모든 값을 1로 채운 ndarray를 반환합니다. default는 float입니다.

In [8]:
arange = np.arange(10)
print(arange)
print(arange.reshape(2,5))
print(arange.reshape(5,-1))

[0 1 2 3 4 5 6 7 8 9]
[[0 1 2 3 4]
 [5 6 7 8 9]]
[[0 1]
 [2 3]
 [4 5]
 [6 7]
 [8 9]]


reshape()는 원하는 형태의 ndarray로 변환해주며, 지정된 사이즈로 변경이 불가능하면 오류가 발생합니다.  
-1를 인자로 사용하면 원래 ndarray와 호환되는 새로운 shape로 변환해줍니다.

### ndarray 데이터 세트 선택 - 인덱싱